<?php

/**
 * This is the model base class for the table "programa_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProgramaTag".
 *
 * Columns in table "programa_tag" available as properties of the model,
 * followed by relations of table "programa_tag" available as properties of the model.
 *
 * @property integer $id_programa_tag
 * @property integer $programa_id_programa
 * @property integer $tag_id_tag
 *
 * @property Programa $programaIdPrograma
 * @property Tag $tagIdTag
 */
abstract class BaseProgramaTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'programa_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProgramaTag|ProgramaTags', $n);
	}

	public static function representingColumn() {
		return 'id_programa_tag';
	}

	public function rules() {
		return array(
			array('programa_id_programa, tag_id_tag', 'required'),
			array('programa_id_programa, tag_id_tag', 'numerical', 'integerOnly'=>true),
			array('id_programa_tag, programa_id_programa, tag_id_tag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'programaIdPrograma' => array(self::BELONGS_TO, 'Programa', 'programa_id_programa'),
			'tagIdTag' => array(self::BELONGS_TO, 'Tag', 'tag_id_tag'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_programa_tag' => Yii::t('app', 'Id Programa Tag'),
			'programa_id_programa' => null,
			'tag_id_tag' => null,
			'programaIdPrograma' => null,
			'tagIdTag' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_programa_tag', $this->id_programa_tag);
		$criteria->compare('programa_id_programa', $this->programa_id_programa);
		$criteria->compare('tag_id_tag', $this->tag_id_tag);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}