<?php

/**
 * This is the model base class for the table "analise".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Analise".
 *
 * Columns in table "analise" available as properties of the model,
 * followed by relations of table "analise" available as properties of the model.
 *
 * @property integer $id_analise
 * @property string $ref_analise
 * @property string $nome_analise
 * @property string $descricao_analise
 * @property string $imagem_analise
 * @property integer $veiculo_id_veiculo
 *
 * @property Veiculo $veiculoIdVeiculo
 * @property AnaliseTag[] $analiseTags
 */
abstract class BaseAnalise extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'analise';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Analise|Analises', $n);
	}

	public static function representingColumn() {
		return 'ref_analise';
	}

	public function rules() {
		return array(
			array('veiculo_id_veiculo', 'required'),
			array('veiculo_id_veiculo', 'numerical', 'integerOnly'=>true),
			array('ref_analise', 'length', 'max'=>45),
			array('nome_analise', 'length', 'max'=>100),
			array('descricao_analise', 'length', 'max'=>512),
			array('imagem_analise', 'length', 'max'=>255),
			array('ref_analise, nome_analise, descricao_analise, imagem_analise', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_analise, ref_analise, nome_analise, descricao_analise, imagem_analise, veiculo_id_veiculo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'veiculoIdVeiculo' => array(self::BELONGS_TO, 'Veiculo', 'veiculo_id_veiculo'),
			'analiseTags' => array(self::HAS_MANY, 'AnaliseTag', 'analise_id_analise'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_analise' => Yii::t('app', 'Id Analise'),
			'ref_analise' => Yii::t('app', 'Ref Analise'),
			'nome_analise' => Yii::t('app', 'Nome Analise'),
			'descricao_analise' => Yii::t('app', 'Descricao Analise'),
			'imagem_analise' => Yii::t('app', 'Imagem Analise'),
			'veiculo_id_veiculo' => null,
			'veiculoIdVeiculo' => null,
			'analiseTags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_analise', $this->id_analise);
		$criteria->compare('ref_analise', $this->ref_analise, true);
		$criteria->compare('nome_analise', $this->nome_analise, true);
		$criteria->compare('descricao_analise', $this->descricao_analise, true);
		$criteria->compare('imagem_analise', $this->imagem_analise, true);
		$criteria->compare('veiculo_id_veiculo', $this->veiculo_id_veiculo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}