<?php

/**
 * This is the model base class for the table "praca".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Praca".
 *
 * Columns in table "praca" available as properties of the model,
 * followed by relations of table "praca" available as properties of the model.
 *
 * @property integer $id_praca
 * @property string $ref_praca
 * @property string $nome_praca
 * @property string $descricao_praca
 * @property integer $veiculo_id_veiculo
 *
 * @property Veiculo $veiculoIdVeiculo
 * @property Programa[] $programas
 */
abstract class BasePraca extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'praca';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Praca|Pracas', $n);
	}

	public static function representingColumn() {
		return 'ref_praca';
	}

	public function rules() {
		return array(
			array('veiculo_id_veiculo', 'required'),
			array('veiculo_id_veiculo', 'numerical', 'integerOnly'=>true),
			array('ref_praca', 'length', 'max'=>45),
			array('nome_praca', 'length', 'max'=>100),
			array('descricao_praca', 'length', 'max'=>512),
			array('ref_praca, nome_praca, descricao_praca', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_praca, ref_praca, nome_praca, descricao_praca, veiculo_id_veiculo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'veiculoIdVeiculo' => array(self::BELONGS_TO, 'Veiculo', 'veiculo_id_veiculo'),
			'programas' => array(self::HAS_MANY, 'Programa', 'praca_id_praca'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_praca' => Yii::t('app', 'Id Praca'),
			'ref_praca' => Yii::t('app', 'Ref Praca'),
			'nome_praca' => Yii::t('app', 'Nome Praca'),
			'descricao_praca' => Yii::t('app', 'Descricao Praca'),
			'veiculo_id_veiculo' => null,
			'veiculoIdVeiculo' => null,
			'programas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_praca', $this->id_praca);
		$criteria->compare('ref_praca', $this->ref_praca, true);
		$criteria->compare('nome_praca', $this->nome_praca, true);
		$criteria->compare('descricao_praca', $this->descricao_praca, true);
		$criteria->compare('veiculo_id_veiculo', $this->veiculo_id_veiculo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}