<?php

/**
 * This is the model base class for the table "analise_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AnaliseTag".
 *
 * Columns in table "analise_tag" available as properties of the model,
 * followed by relations of table "analise_tag" available as properties of the model.
 *
 * @property integer $id_analise_tag
 * @property integer $analise_id_analise
 * @property integer $tag_id_tag
 *
 * @property Analise $analiseIdAnalise
 * @property Tag $tagIdTag
 */
abstract class BaseAnaliseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'analise_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AnaliseTag|AnaliseTags', $n);
	}

	public static function representingColumn() {
		return 'id_analise_tag';
	}

	public function rules() {
		return array(
			array('analise_id_analise, tag_id_tag', 'required'),
			array('analise_id_analise, tag_id_tag', 'numerical', 'integerOnly'=>true),
			array('id_analise_tag, analise_id_analise, tag_id_tag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'analiseIdAnalise' => array(self::BELONGS_TO, 'Analise', 'analise_id_analise'),
			'tagIdTag' => array(self::BELONGS_TO, 'Tag', 'tag_id_tag'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_analise_tag' => Yii::t('app', 'Id Analise Tag'),
			'analise_id_analise' => null,
			'tag_id_tag' => null,
			'analiseIdAnalise' => null,
			'tagIdTag' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_analise_tag', $this->id_analise_tag);
		$criteria->compare('analise_id_analise', $this->analise_id_analise);
		$criteria->compare('tag_id_tag', $this->tag_id_tag);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}