<?php

/**
 * This is the model base class for the table "tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tag".
 *
 * Columns in table "tag" available as properties of the model,
 * followed by relations of table "tag" available as properties of the model.
 *
 * @property integer $id_tag
 * @property string $ref_tag
 * @property string $nome_tag
 *
 * @property AnaliseTag[] $analiseTags
 * @property ProgramaTag[] $programaTags
 */
abstract class BaseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tag|Tags', $n);
	}

	public static function representingColumn() {
		return 'ref_tag';
	}

	public function rules() {
		return array(
			array('ref_tag, nome_tag', 'length', 'max'=>45),
			array('ref_tag, nome_tag', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tag, ref_tag, nome_tag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'analiseTags' => array(self::HAS_MANY, 'AnaliseTag', 'tag_id_tag'),
			'programaTags' => array(self::HAS_MANY, 'ProgramaTag', 'tag_id_tag'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tag' => Yii::t('app', 'Id Tag'),
			'ref_tag' => Yii::t('app', 'Ref Tag'),
			'nome_tag' => Yii::t('app', 'Nome Tag'),
			'analiseTags' => null,
			'programaTags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tag', $this->id_tag);
		$criteria->compare('ref_tag', $this->ref_tag, true);
		$criteria->compare('nome_tag', $this->nome_tag, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}