<?php

/**
 * This is the model base class for the table "log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Log".
 *
 * Columns in table "log" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_log
 * @property string $usuario_log
 * @property string $ip_log
 * @property string $acao_log
 * @property string $ref_log
 * @property string $data_log
 * @property string $descricao_log
 *
 */
abstract class BaseLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Log|Logs', $n);
	}

	public static function representingColumn() {
		return 'usuario_log';
	}

	public function rules() {
		return array(
			array('usuario_log', 'length', 'max'=>50),
			array('ip_log, acao_log, ref_log', 'length', 'max'=>45),
			array('descricao_log', 'length', 'max'=>512),
			array('data_log', 'safe'),
			array('usuario_log, ip_log, acao_log, ref_log, data_log, descricao_log', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_log, usuario_log, ip_log, acao_log, ref_log, data_log, descricao_log', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_log' => Yii::t('app', 'Id Log'),
			'usuario_log' => Yii::t('app', 'Usuario Log'),
			'ip_log' => Yii::t('app', 'Ip Log'),
			'acao_log' => Yii::t('app', 'Acao Log'),
			'ref_log' => Yii::t('app', 'Ref Log'),
			'data_log' => Yii::t('app', 'Data Log'),
			'descricao_log' => Yii::t('app', 'Descricao Log'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_log', $this->id_log);
		$criteria->compare('usuario_log', $this->usuario_log, true);
		$criteria->compare('ip_log', $this->ip_log, true);
		$criteria->compare('acao_log', $this->acao_log, true);
		$criteria->compare('ref_log', $this->ref_log, true);
		$criteria->compare('data_log', $this->data_log, true);
		$criteria->compare('descricao_log', $this->descricao_log, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}