<?php

/**
 * This is the model base class for the table "arquivo_historico".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ArquivoHistorico".
 *
 * Columns in table "arquivo_historico" available as properties of the model,
 * followed by relations of table "arquivo_historico" available as properties of the model.
 *
 * @property integer $id_arquivo_historico
 * @property integer $fk_id_arquivo
 * @property string $ref_arquivo
 * @property string $nome_arquivo
 * @property string $caminho_arquivo
 *
 * @property Arquivo $fkIdArquivo
 */
abstract class BaseArquivoHistorico extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'arquivo_historico';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ArquivoHistorico|ArquivoHistoricos', $n);
	}

	public static function representingColumn() {
		return 'ref_arquivo';
	}

	public function rules() {
		return array(
			array('fk_id_arquivo, ref_arquivo, nome_arquivo, caminho_arquivo', 'required'),
			array('fk_id_arquivo', 'numerical', 'integerOnly'=>true),
			array('ref_arquivo', 'length', 'max'=>45),
			array('nome_arquivo', 'length', 'max'=>100),
			array('caminho_arquivo', 'length', 'max'=>512),
			array('id_arquivo_historico, fk_id_arquivo, ref_arquivo, nome_arquivo, caminho_arquivo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fkIdArquivo' => array(self::BELONGS_TO, 'Arquivo', 'fk_id_arquivo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_arquivo_historico' => Yii::t('app', 'Id Arquivo Historico'),
			'fk_id_arquivo' => null,
			'ref_arquivo' => Yii::t('app', 'Ref Arquivo'),
			'nome_arquivo' => Yii::t('app', 'Nome Arquivo'),
			'caminho_arquivo' => Yii::t('app', 'Caminho Arquivo'),
			'fkIdArquivo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_arquivo_historico', $this->id_arquivo_historico);
		$criteria->compare('fk_id_arquivo', $this->fk_id_arquivo);
		$criteria->compare('ref_arquivo', $this->ref_arquivo, true);
		$criteria->compare('nome_arquivo', $this->nome_arquivo, true);
		$criteria->compare('caminho_arquivo', $this->caminho_arquivo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}