<?php

/**
 * This is the model base class for the table "cliente".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cliente".
 *
 * Columns in table "cliente" available as properties of the model,
 * followed by relations of table "cliente" available as properties of the model.
 *
 * @property integer $id_cliente
 * @property string $ref_cliente
 * @property string $nome_cliente
 * @property string $imagem_cliente
 *
 * @property Estudo[] $estudos
 */
abstract class BaseCliente extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cliente';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cliente|Clientes', $n);
	}

	public static function representingColumn() {
		return 'ref_cliente';
	}

	public function rules() {
		return array(
			array('ref_cliente, nome_cliente, imagem_cliente', 'required'),
			array('ref_cliente', 'length', 'max'=>45),
            array('ref_cliente','unique', 'message'=>'Essa Chave Já existe.'),

            array('nome_cliente', 'length', 'max'=>100),
			array('imagem_cliente', 'length', 'max'=>255),
			array('id_cliente, ref_cliente, nome_cliente, imagem_cliente', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'estudos' => array(self::HAS_MANY, 'Estudo', 'cliente_id_cliente'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_cliente' => Yii::t('app', 'Id Cliente'),
			'ref_cliente' => Yii::t('app', 'Ref Cliente'),
			'nome_cliente' => Yii::t('app', 'Nome Cliente'),
			'imagem_cliente' => Yii::t('app', 'Imagem Cliente'),
			'estudos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_cliente', $this->id_cliente);
		$criteria->compare('ref_cliente', $this->ref_cliente, true);
		$criteria->compare('nome_cliente', $this->nome_cliente, true);
		$criteria->compare('imagem_cliente', $this->imagem_cliente, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}