<?php

/**
 * This is the model base class for the table "praca_programa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PracaPrograma".
 *
 * Columns in table "praca_programa" available as properties of the model,
 * followed by relations of table "praca_programa" available as properties of the model.
 *
 * @property integer $praca_id_praca
 * @property integer $programa_id_programa
 *
 * @property Arquivo[] $arquivos
 * @property Arquivo[] $arquivos1
 */
abstract class BasePracaPrograma extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'praca_programa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PracaPrograma|PracaProgramas', $n);
	}

	public static function representingColumn() {
		return array(
			'praca_id_praca',
			'programa_id_programa',
		);
	}

	public function rules() {
		return array(
			array('praca_id_praca, programa_id_programa', 'required'),
			array('praca_id_praca, programa_id_programa', 'numerical', 'integerOnly'=>true),
			array('praca_id_praca, programa_id_programa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'arquivos' => array(self::HAS_MANY, 'Arquivo', 'praca_programa_praca_id_praca'),
			'arquivos1' => array(self::HAS_MANY, 'Arquivo', 'praca_programa_programa_id_programa'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'praca_id_praca' => null,
			'programa_id_programa' => null,
			'arquivos' => null,
			'arquivos1' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('praca_id_praca', $this->praca_id_praca);
		$criteria->compare('programa_id_programa', $this->programa_id_programa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}