<?php

/**
 * This is the model base class for the table "veiculo_has_estudo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VeiculoHasEstudo".
 *
 * Columns in table "veiculo_has_estudo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $veiculo_id_veiculo
 * @property integer $estudo_id_estudo
 *
 */
abstract class BaseVeiculoHasEstudo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'veiculo_has_estudo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VeiculoHasEstudo|VeiculoHasEstudos', $n);
	}

	public static function representingColumn() {
		return array(
			'veiculo_id_veiculo',
			'estudo_id_estudo',
		);
	}

	public function rules() {
		return array(
			array('veiculo_id_veiculo, estudo_id_estudo', 'required'),
			array('veiculo_id_veiculo, estudo_id_estudo', 'numerical', 'integerOnly'=>true),
			array('veiculo_id_veiculo, estudo_id_estudo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'veiculo_id_veiculo' => null,
			'estudo_id_estudo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('veiculo_id_veiculo', $this->veiculo_id_veiculo);
		$criteria->compare('estudo_id_estudo', $this->estudo_id_estudo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}