<?php

/**
 * This is the model base class for the table "estudo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Estudo".
 *
 * Columns in table "estudo" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_estudo
 * @property string $ref_estudo
 * @property string $nome_estudo
 * @property string $caminho_estudo
 * @property string $cliente_estudo
 * @property integer $ativo_estudo
 *
 */
abstract class BaseEstudo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estudo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Estudo|Estudos', $n);
	}

	public static function representingColumn() {
		return 'ref_estudo';
	}

	public function rules() {
		return array(
			array('ref_estudo, nome_estudo, caminho_estudo, cliente_estudo, ativo_estudo', 'required'),
			array('ativo_estudo', 'numerical', 'integerOnly'=>true),
			array('ref_estudo', 'length', 'max'=>45),
			array('nome_estudo, cliente_estudo', 'length', 'max'=>100),
			array('caminho_estudo', 'length', 'max'=>255),
			array('id_estudo, ref_estudo, nome_estudo, caminho_estudo, cliente_estudo, ativo_estudo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_estudo' => Yii::t('app', 'Id Estudo'),
			'ref_estudo' => Yii::t('app', 'Ref Estudo'),
			'nome_estudo' => Yii::t('app', 'Nome Estudo'),
			'caminho_estudo' => Yii::t('app', 'Caminho Estudo'),
			'cliente_estudo' => Yii::t('app', 'Cliente Estudo'),
			'ativo_estudo' => Yii::t('app', 'Ativo Estudo'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_estudo', $this->id_estudo);
		$criteria->compare('ref_estudo', $this->ref_estudo, true);
		$criteria->compare('nome_estudo', $this->nome_estudo, true);
		$criteria->compare('caminho_estudo', $this->caminho_estudo, true);
		$criteria->compare('cliente_estudo', $this->cliente_estudo, true);
		$criteria->compare('ativo_estudo', $this->ativo_estudo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}