<?php

/**
 * This is the model base class for the table "veiculo_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VeiculoTag".
 *
 * Columns in table "veiculo_tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $tag_id_tag
 * @property integer $veiculo_id_veiculo
 *
 */
abstract class BaseVeiculoTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'veiculo_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VeiculoTag|VeiculoTags', $n);
	}

	public static function representingColumn() {
		return array(
			'tag_id_tag',
			'veiculo_id_veiculo',
		);
	}

	public function rules() {
		return array(
			array('tag_id_tag, veiculo_id_veiculo', 'required'),
			array('tag_id_tag, veiculo_id_veiculo', 'numerical', 'integerOnly'=>true),
			array('tag_id_tag, veiculo_id_veiculo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tag_id_tag' => null,
			'veiculo_id_veiculo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tag_id_tag', $this->tag_id_tag);
		$criteria->compare('veiculo_id_veiculo', $this->veiculo_id_veiculo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}