<?php

/**
 * This is the model base class for the table "veiculo_praca_programa".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VeiculoPracaPrograma".
 *
 * Columns in table "veiculo_praca_programa" available as properties of the model,
 * followed by relations of table "veiculo_praca_programa" available as properties of the model.
 *
 * @property integer $fk_id_veiculo
 * @property integer $fk_id_praca
 * @property integer $fk_id_programa
 *
 * @property Arquivo[] $arquivos
 * @property Arquivo[] $arquivos1
 * @property Arquivo[] $arquivos2
 * @property Programa $fkIdPrograma
 * @property VeiculoPraca $fkIdVeiculo
 * @property VeiculoPraca $fkIdPraca
 */
abstract class BaseVeiculoPracaPrograma extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'veiculo_praca_programa';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VeiculoPracaPrograma|VeiculoPracaProgramas', $n);
	}

	public static function representingColumn() {
		return array(
			'fk_id_veiculo',
			'fk_id_praca',
			'fk_id_programa',
		);
	}

	public function rules() {
		return array(
			array('fk_id_veiculo, fk_id_praca, fk_id_programa', 'required'),
			array('fk_id_veiculo, fk_id_praca, fk_id_programa', 'numerical', 'integerOnly'=>true),
			array('fk_id_veiculo, fk_id_praca, fk_id_programa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'arquivos' => array(self::HAS_MANY, 'Arquivo', 'fk_id_veiculo'),
			'arquivos1' => array(self::HAS_MANY, 'Arquivo', 'fk_id_praca'),
			'arquivos2' => array(self::HAS_MANY, 'Arquivo', 'fk_id_programa'),
			'fkIdPrograma' => array(self::BELONGS_TO, 'Programa', 'fk_id_programa'),
			'fkIdVeiculo' => array(self::BELONGS_TO, 'VeiculoPraca', 'fk_id_veiculo'),
			'fkIdPraca' => array(self::BELONGS_TO, 'VeiculoPraca', 'fk_id_praca'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fk_id_veiculo' => null,
			'fk_id_praca' => null,
			'fk_id_programa' => null,
			'arquivos' => null,
			'arquivos1' => null,
			'arquivos2' => null,
			'fkIdPrograma' => null,
			'fkIdVeiculo' => null,
			'fkIdPraca' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fk_id_veiculo', $this->fk_id_veiculo);
		$criteria->compare('fk_id_praca', $this->fk_id_praca);
		$criteria->compare('fk_id_programa', $this->fk_id_programa);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}