<?php

/**
 * This is the model base class for the table "tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Tag".
 *
 * Columns in table "tag" available as properties of the model,
 * followed by relations of table "tag" available as properties of the model.
 *
 * @property integer $id_tag
 * @property string $ref_tag
 * @property string $nome_tag
 * @property string $tipo_tag
 *
 * @property Analise[] $analises
 * @property Arquivo[] $arquivos
 * @property Programa[] $programas
 */
abstract class BaseTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tag|Tags', $n);
	}

	public static function representingColumn() {
		return 'nome_tag';
	}

	public function rules() {
		return array(
			array('tipo_tag', 'required'),
			array('ref_tag, nome_tag, tipo_tag', 'length', 'max'=>45),
			array('ref_tag, nome_tag', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tag, ref_tag, nome_tag, tipo_tag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'analises' => array(self::MANY_MANY, 'Analise', 'analise_tag(fk_id_tag, fk_id_analise)'),
			'arquivos' => array(self::MANY_MANY, 'Arquivo', 'arquivo_tag(fk_id_tag, fk_id_arquivo)'),
			'programas' => array(self::MANY_MANY, 'Programa', 'programa_tag(fk_id_tag, fk_id_programa)'),
		);
	}

	public function pivotModels() {
		return array(
			'analises' => 'AnaliseTag',
			'arquivos' => 'ArquivoTag',
			'programas' => 'ProgramaTag',
		);
	}

	public function attributeLabels() {
		return array(
			'id_tag' => Yii::t('app', 'Id'),
			'ref_tag' => Yii::t('app', 'Ref'),
			'nome_tag' => Yii::t('app', 'Nome'),
			'tipo_tag' => Yii::t('app', 'Tipo'),
			'analises' => null,
			'arquivos' => null,
			'programas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tag', $this->id_tag);
		$criteria->compare('ref_tag', $this->ref_tag, true);
		$criteria->compare('nome_tag', $this->nome_tag, true);
		$criteria->compare('tipo_tag', $this->tipo_tag, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

}