<?php

/**
 * This is the model base class for the table "veiculo_analise".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VeiculoAnalise".
 *
 * Columns in table "veiculo_analise" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $fk_id_veiculo
 * @property integer $fk_id_analise
 *
 */
abstract class BaseVeiculoAnalise extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'veiculo_analise';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VeiculoAnalise|VeiculoAnalises', $n);
	}

	public static function representingColumn() {
		return array(
			'fk_id_veiculo',
			'fk_id_analise',
		);
	}

	public function rules() {
		return array(
			array('fk_id_veiculo, fk_id_analise', 'required'),
			array('fk_id_veiculo, fk_id_analise', 'numerical', 'integerOnly'=>true),
			array('fk_id_veiculo, fk_id_analise', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fk_id_veiculo' => null,
			'fk_id_analise' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fk_id_veiculo', $this->fk_id_veiculo);
		$criteria->compare('fk_id_analise', $this->fk_id_analise);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}