<?php

/**
 * This is the model base class for the table "arquivo_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ArquivoTag".
 *
 * Columns in table "arquivo_tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $fk_id_tag
 * @property integer $fk_id_arquivo
 *
 */
abstract class BaseArquivoTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'arquivo_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ArquivoTag|ArquivoTags', $n);
	}

	public static function representingColumn() {
		return array(
			'fk_id_tag',
			'fk_id_arquivo',
		);
	}

	public function rules() {
		return array(
			array('fk_id_tag, fk_id_arquivo', 'required'),
			array('fk_id_tag, fk_id_arquivo', 'numerical', 'integerOnly'=>true),
			array('fk_id_tag, fk_id_arquivo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fk_id_tag' => null,
			'fk_id_arquivo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fk_id_tag', $this->fk_id_tag);
		$criteria->compare('fk_id_arquivo', $this->fk_id_arquivo);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}