<?php

/**
 * This is the model base class for the table "estudo_has_tag".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EstudoHasTag".
 *
 * Columns in table "estudo_has_tag" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $estudo_id_estudo
 * @property integer $tag_id_tag
 *
 */
abstract class BaseEstudoHasTag extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'estudo_has_tag';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EstudoHasTag|EstudoHasTags', $n);
	}

	public static function representingColumn() {
		return array(
			'estudo_id_estudo',
			'tag_id_tag',
		);
	}

	public function rules() {
		return array(
			array('estudo_id_estudo, tag_id_tag', 'required'),
			array('estudo_id_estudo, tag_id_tag', 'numerical', 'integerOnly'=>true),
			array('estudo_id_estudo, tag_id_tag', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'estudo_id_estudo' => null,
			'tag_id_tag' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('estudo_id_estudo', $this->estudo_id_estudo);
		$criteria->compare('tag_id_tag', $this->tag_id_tag);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}